# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily" # Check for updates every day
      time: "00:00"
    open-pull-requests-limit: 10
    allow:
      - dependency-type: "all" # Met à jour toutes les dépendances
    commit-message:
      prefix: "chore(deps):"
    labels:
      - "dependencies"
    reviewers:
      - "sony-level" # Remplace par ton pseudo GitHub si nécessaire
    assignees:
      - "sony-level"

    
        
